### ISSUE TITLE
run nice-slam for open dataset, IndexError: list index out of range

### ISSUE THREAD

**Issue by parastoobakhtiarii** [cvg/nice-slam#125]
![Image](https://github.com/user-attachments/assets/0510ee38-2ffb-441d-9188-5005d9151bdb)

Hi, 
I hope you are doing well.
thank you for the great documentation.
I am trying to run nice-slam on [Terrasentia dataset](https://uofi.app.box.com/s/l7e0okjxkq1vzz77goac2bu1my81ad9d/folder/167861574990), I'm using `python 3.9 ` and 
```
python -c "import torch; print(torch.__version__); print(torch.version.cuda); print(torch.cuda.is_available())"
2.5.1+cu121
12.1
True
```
I get this error:
2025-03-19 15:19:34,054 - INFO - Running NICE-SLAM with config: configs/Terrasentia/terrasentia.yaml
2025-03-19 15:19:34,054 - INFO - Output directory: /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia
2025-03-19 15:19:34,054 - INFO - Using NICE-SLAM: True
INFO: The output folder is /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia
INFO: The GT, generated and residual depth/color images can be found under /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia/tracking_vis/ and /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia/mapping_vis/
INFO: The mesh can be found under /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia/mesh/
INFO: The checkpoint can be found under /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia/ckpt/
2025-03-19 15:19:34,479 - INFO - NICE-SLAM initialized successfully.
Process Process-2:
Traceback (most recent call last):
  File "/home/asaas/anaconda3/envs/nice-slam/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/asaas/anaconda3/envs/nice-slam/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/asaas/DATA/Parastou/nice-slam/src/NICE_SLAM.py", line 276, in mapping
    self.mapper.run()
  File "/media/asaas/DATA/Parastou/nice-slam/src/Mapper.py", line 544, in run
    idx, gt_color, gt_depth, gt_c2w = self.frame_reader[0]
  File "/media/asaas/DATA/Parastou/nice-slam/src/utils/datasets.py", line 78, in __getitem__
    color_path = self.color_paths[index]
IndexError: list index out of range

Would you please tell me what can be the potential issue?

my dataset contains 3998 rgb images and 3998 depth images. the attached image. and this is the yaml file:
```
inherit_from: configs/Own/own.yaml

cam:
  H: 480  # Image height
  W: 640  # Image width
  fx: 342.40289471  # Focal length in x (from left camera intrinsics)
  fy: 342.20510857  # Focal length in y (from left camera intrinsics)
  cx: 408.75398427  # Principal point x (from left camera intrinsics)
  cy: 220.34050007  # Principal point y (from left camera intrinsics)
  png_depth_scale: 1000.0  # For depth image in png format
  crop_edge: 0

mapping:
  bound: [[-10, 10], [-5, 5], [-1, 3]]  # Adjust based on field size and camera range
  marching_cubes_bound: [[-10, 10], [-5, 5], [-1, 3]]  # Same as bound for consistency

data:
  input_folder: /media/asaas/DATA/Parastou/nice-slam/Datasets/Terrasentia
  output: /media/asaas/DATA/Parastou/nice-slam/output/Terrasentia

model:
  use_color: True
  use_depth: True
  voxel_size: 0.05
  truncation: 0.1

optimization:
  num_iterations: 1000
  learning_rate: 0.001

output:
  save_mesh: True
  save_trajectory: True
```
Thanks.
